version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "obetomuniz"
    default_labels:
      - "dependency"
    allowed_updates:
      - match:
          update_type: "direct"
